#!/bin/sh


# packages
echo "# Install few basic packages"
apk add --update --no-cache --quiet \
    bash \
    gettext \
    git \
    jq \
    openssh \
    unzip \
    wget

# composer
echo "# Install composer"
EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig 2>/dev/null)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

if [ "$COMPOSER_VERSION" != "" ]; then
  INSTALL_COMPOSER_VERSION="$COMPOSER_VERSION"
else
  INSTALL_COMPOSER_VERSION=$(curl 'https://api.github.com/repos/composer/composer/releases/latest' 2>/dev/null | jq -r '.tag_name')
fi

php composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --version=${INSTALL_COMPOSER_VERSION} --quiet
RESULT=$?
chmod go+w /usr/local/bin/composer
rm composer-setup.php
